### ISSUE TITLE
关于QMI8658C驱动

### ISSUE THREAD

**Issue by conghuang** [jvadair/scribbl#1]
您好，我看到代码中含有“from i2cdrivers import CST816, QMI8658C  # Touch and 6-axis sensor drivers”但是我在默认的固件中没有发现该模块和驱动，如果您能提供或指出来源，不胜感谢

**Comment by jvadair** [comment]
Thanks for noticing this. I have now uploaded the relevant file. I fear I have missed some other things as well when uploading the project, though I am now re-making the watch software in C++ due to some issues I had writing it in MicroPython. Please let me know if I missed any other components.
